/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author trussiriyothin
 */
public class method extends javax.swing.JFrame {

    /**
     * Creates new form method
     */
    public method() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("โปรแกรมดูข้อมูล");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Data");

        jLabel2.setText("Please select the menu");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jTextArea1.setText("1.Add Data"+"\n"+"2.Check Data new"+"\n"+"3.Check Data All"
                +"\n"+"4.Contact"+"\n"+"5.exit");
 
        
        Case c = new Case();       
        int i = 0;
        
        System.out.println("1.Add Data"+"\n"+"2.Check Data new"+"\n"+"3.Check Data All"
                +"\n"+"4.Contact"+"\n"+"5.exit"+"\n");
              
        String menu;
       // do{
        System.out.print("Please select the menu : ");        
        menu = jTextField1.getText();

        switch (menu) {                                    
            case "aa" : { try {
                c.Case1();
            } catch (IOException ex) {
                Logger.getLogger(method.class.getName()).log(Level.SEVERE, null, ex);
            }
} break;
            case "ss" : { try {
                c.Case2();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(method.class.getName()).log(Level.SEVERE, null, ex);
            }
} break;
            case "dd" : { try {
                c.Case3();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(method.class.getName()).log(Level.SEVERE, null, ex);
            }
} break;          
            case "ff" : { c.Case4(); } break;
 
        } System.out.println("\n"+"Thank You"+"\n");        
       // }while(menu < 5);          
    
    }                                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        
    }                                           
    public void jTextArea1(){
        System.out.println("1.Add Data"+"\n"+"2.Check Data new"+"\n"+"3.Check Data All"
                +"\n"+"4.Contact"+"\n"+"5.exit"+"\n");
        jTextArea1.setText("1.Add Data"+"\n"+"2.Check Data new"+"\n"+"3.Check Data All"
                +"\n"+"4.Contact"+"\n"+"5.exit");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(method.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(method.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(method.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(method.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new method().setVisible(true);
            }
        });
    }
    class Case{
    
    String data1;
    
    void Case1() throws IOException{
        
        Scanner scanner = new Scanner(System.in);
        System.out.print("\n"+"Please type the Data : ");
        jTextArea1.setText("Please type the Data : ");
        
        data1 = jTextArea2.getText();
        System.out.println("\n"+"Complete");
        jTextArea1.setText("Thank you");
                      
        File file = new File ("data.txt");
            if (!file.exists()){
                file.createNewFile();
            }       
        try (FileWriter writer = new FileWriter("data.txt",true)) {           
                writer.write(data1 + "\n");
                }catch (IOException e){
                         System.out.print(e);}               
}
        
    void Case2() throws FileNotFoundException{
        
        try{
        File file = new File ("data.txt");
        Scanner checkFile = new Scanner(file);
        
        String keep = checkFile.nextLine();
        System.out.println(keep);
        jTextArea2.setText(keep);
        }catch (Exception e){}
        System.out.println("\n"+"Complete"); 
    
}

    void Case3() throws FileNotFoundException{
        
        try{
            
        String [] arrayData = new String[1000];
        int count = 0;    
        File file = new File ("data.txt");
        Scanner checkFile = new Scanner(file);
        
        while (checkFile.hasNextLine()){
            arrayData [count] = checkFile.nextLine();
            count ++;
        }for(int i = 0; i < count; i++){
                System.out.println("\n"+arrayData[i]);
                jTextArea2.setText(arrayData[i]);
                
        }
        }catch (Exception e){}
        System.out.println("\n"+"Complete");  
    }
    
    void Case4(){
        
        System.out.print("please contact nona");
        jTextArea2.setText("please contact nona");
        
    }
    void Case5(){
        jTextArea2.setText("exit");
        
    }
}  
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
